### PR TITLE
review.sh: update LATESTRD field

### PR DESCRIPTION
**Pull request by annevk**
Helps with https://github.com/whatwg/sg/issues/124.

### CODE REVIEW

**Review by domenic — APPROVED** [review]
Looks good, and shellcheck passes. You've tested locally?

**Comment by annevk** [comment]
Yeah, the one thing it does not handle is going from not having this to needing this. I think doing a bit of additional work at that point is fine though.

**Comment by annevk** [comment]
I just realized that one thing that will happen here is that LATESTRD gets copied over to the Review Draft as well. So we have to make a choice:

1. Allow that, but use one of the new Bikeshed features to exclude it from being used.
2. Remove it here as part of the script.

I think I prefer 1 as having less differences between the source documents seems good.

**Comment by domenic** [comment]
I agree with your reasoning.

**Pull request merged**
