### PR TITLE
Tolerate no trailing .git when determining SHORTNAME

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Yes, this is an hilarious amount of escaping!

**Comment by annevk** [comment]
Why is this needed?

I'm wondering if it would be better to hardcode the couple of exceptions we have here with respect to shortname in factory.json and propagate it as input parameter.

**Comment by annevk** [comment]
Sorry, I was thinking about the wrong thing. We should probably indicate we can clean this up post-transition.

**Comment by foolip** [comment]
I'll send a follow-up that does something much simpler for GitHub Actions. The other path will then be for local, where it actually makes sense to handle both cases, and will continue to work on Travis.

**Comment by foolip** [comment]
Sent https://github.com/whatwg/whatwg.org/pull/326.

**Pull request merged**
