### PR TITLE
Make SHORTNAME detection on GitHub Actions much simpler

### PR DESCRIPTION
**Pull request by foolip**
The complicated thing is still used locally and on Travis.

### CODE REVIEW

**Comment by foolip** [comment]
Here I also organized things a bit into constants, environment variables and local variables.

**Comment by annevk** [comment]
So we basically have this because of compat/console/streams not using their shortname as their .bs name, right? @domenic any thoughts on renaming them instead?

**Comment by domenic** [comment]
Renaming is quite disruptive and loses the entire file history in the GitHub UI. I think adding a single line in the build script is a very small price to pay.

(I'm not really sure why we'd expand that single line into 5 lines as this PR does, though...)

**Comment by annevk** [comment]
Well, you wouldn't lose history for the links we advocate, e.g., https://github.com/whatwg/compat/commits, and I think blame isn't impacted either, but that's fair.

**Comment by foolip** [comment]
> I'm not really sure why we'd expand that single line into 5 lines as this PR does, though...

Things work without this change, but interpreting that `sed` command is very hard. This is a follow-up to https://github.com/whatwg/whatwg.org/pull/325 to make it more obvious why it's like that (in the future: for local builds only). But if this just looks more convoluted, I could either:
- abandon this
- just use the directory name in the else branch

**Comment by annevk** [comment]
I would abandon, but explain the complexity in a comment.

**Comment by domenic** [comment]
Given that the sed command still exists, it doesn't feel like a win to just add a second path where the sed command is bypassed. Now one has to understand `complicated thing + simple thing`, which seems slightly worse than having to understand `complicated thing` by itself.

**Comment by foolip** [comment]
I've sent https://github.com/whatwg/whatwg.org/pull/327 instead.

**Pull request closed without merging**
