### PR TITLE
Remove "WHATWG" prefix from the <h2> version of the title

### LINKED ISSUE #147: Update script to make making <h2> and <title>s of documents consistent with the rest of whatwg.org
Update script to make making `<h2>` and `<title>`s of documents consistent with the rest of whatwg.org.

This is the script part of https://github.com/whatwg/sg/issues/44

### PR DESCRIPTION
**Pull request by othermaciej**
Fixes #147
Policies not regenerated yet to avoid reintroducing paren bugs; will do that after #146 lands.

### CODE REVIEW

**Comment by domenic** [comment]
I suppose we should wait to merge this until https://github.com/whatwg/sg/pull/55 first gets merged?

**Comment by othermaciej** [comment]
@domenic I think that would be best.

**Comment by annevk** [comment]
This now needs to be rebased as this repository no longer hosts those files, just the scripts.

**Comment by annevk** [comment]
(I would be happy to do that work btw and land both this and the whatwg/sg change, which both seem editorial enough for me to do that.)

**Comment by othermaciej** [comment]
@annevk Please do rebase it. I don't have the access to do so. I merged the SG repo PR.

**Comment by annevk** [comment]
You should have access to rebase this branch. You cannot commit to master per current settings, but that's it.

**Comment by annevk** [comment]
Anyway, I've done it.

**Comment by othermaciej** [comment]
GitHub UI said I did not have permissions to rebase it, which I find a bit mysterious, since I have permission to make a PR in the first place.

**Comment by annevk** [comment]
Aah, that is about rebasing and committing to master at once. You'd have to locally run "git rebase master" and then "git push --force" once you're done.

**Pull request merged**
