### PR TITLE
Add Test Utils logo

### PR DESCRIPTION
**Pull request by annevk**
@jgraham what do you think? If this works I'll add the PNG, add it to the Twitter account, and we can call it a day.

### CODE REVIEW

**Comment by annevk** [comment]
Preview at https://raw.githubusercontent.com/whatwg/whatwg.org/cc8e26441c458c2f54a194804a6c21c0f1b12a6c/resources.whatwg.org/logo-testutils.svg it seems.

**Comment by jgraham** [comment]
Sure. I think I would have gone with a test tube or conical flask or something, but I like the way this breaks out of the circle, and it matches the precedent of the whatwg / html logo.

**Comment by annevk** [comment]
For some reason CI fails on obtaining the HTML checker? @sideshowbarker can you take a look?

**Comment by sideshowbarker** [comment]
> For some reason CI fails on obtaining the HTML checker? @sideshowbarker can you take a look?

Sorry, a backwards-incompatible dependabot change broke the HTML-checker build. Fixed now (and re-ran CI here, and it’s now all green)

**Review by sideshowbarker — APPROVED** [review]

**Pull request merged**
