### PR TITLE
Add parse error table style

### PR DESCRIPTION
**Pull request by inikulin**
Required for https://github.com/whatwg/html/pull/2701#discussion_r117782153

### CODE REVIEW

**Comment by inikulin** [comment]
Hmm, seems like file had mixed line endings. My editor changed them to LF.

**Comment by domenic** [comment]
Since this is HTML-specific, I think it would make sense in the `<style>` block at the top of the HTML source file?

**Comment by annevk** [comment]
Also, is HTML not using standard.css from https://github.com/whatwg/resources.whatwg.org? If not, we should maybe fix that.

**Comment by inikulin** [comment]
> Since this is HTML-specific, I think it would make sense in the <style> block at the top of the HTML source file?

Oh, I've missed an elephant in the room. Will move it there then. Closing this one.

**Pull request closed without merging**
