### PR TITLE
Working Mode is in Markdown now

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/sg/pull/88. Needs to be merged afterwards. And also requires #295 and rebasing.

### CODE REVIEW

**Comment by annevk** [comment]
See https://github.com/whatwg/sg/pull/88#issuecomment-595805606 and https://github.com/whatwg/whatwg.org/issues/291 for context of the recent changes.

**Comment by foolip** [comment]
I've compared the built output with these changes and it looks like an `<hr>` is gone from all the converted files. Is that known/intended?

**Comment by foolip** [comment]
Yes, that's very much intentional, I see it in the code now :)

**Comment by foolip** [comment]
"Needs to be merged afterwards." left in commit message because I rebased. Oh well.

**Comment by annevk** [comment]
Thanks @foolip!

**Pull request merged**
