### PR TITLE
Deploy to marquee using GitHub actions

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by annevk** [comment]
To be clear, I'm convinced it's worth going in this direction. Feel free to land this.

**Comment by foolip** [comment]
I've filed https://github.com/whatwg/meta/issues/173 to track the migration for all of our repositories. Before I land this I'll prepare a PR for a few other repos too, to shake out any unexpected issues with the different types of setups we have.

**Comment by foolip** [comment]
Alright, I'll make a backup of marquee and deploy this now, to see that this doesn't blow up the world before proceeding with other things that deploy to marquee.

**Comment by foolip** [comment]
https://github.com/whatwg/whatwg.org/runs/762311824 worked after I fixed the secrets.

**Comment by annevk** [comment]
I think this regressed us a tiny bit as before we had shellcheck run always and deploy only run on master.

**Comment by foolip** [comment]
You're right, I'll fix that.

**Comment by foolip** [comment]
Fixed in https://github.com/whatwg/whatwg.org/pull/323.

**Pull request merged**
