### PR TITLE
Host images.whatwg.org and n.whatwg.org here

### PR DESCRIPTION
**Pull request by annevk**
I created these through wget -r coupled with some cleaning up and copying an .htaccess line from src/.htaccess.

### CODE REVIEW

**Comment by annevk** [comment]
Note that this still requires updates to the rsync line in order to work (and the domains haven't moved yet).

**Comment by foolip** [comment]
Did you deliberately not include https://n.whatwg.org/README?

**Comment by annevk** [comment]
Yes, it's inaccurate.

**Comment by annevk** [comment]
I guess I could have added redirect 410 /README.

**Comment by foolip** [comment]
Meh, doesn't matter.

**Pull request merged**
