### PR TITLE
    Add script for expanding/un-expanding MDN annos

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change adds an event listener for expanding and un-expanding MDN annos.

Blocks https://github.com/tabatkins/bikeshed/pull/1710

### CODE REVIEW

**Comment by domenic** [comment]
I'm sad about Bikeshed not outputting them in the correct position like Wattsi does.

Do you mind if I push a commit that changes up the style / JS minutiae here a good bit?

**Comment by sideshowbarker** [comment]
> I'm sad about Bikeshed not outputting them in the correct position like Wattsi does.

Yeah, I think that may change in the long term. I will try to make time myself to write up a patch for it, if Tab doesn’t get to it first.

> Do you mind if I push a commit that changes up the style / JS minutiae here a good bit?

Don’t mind at all. I know the styles especially leave a lot room for improvement…

**Comment by sideshowbarker** [comment]
> > I'm sad about Bikeshed not outputting them in the correct position like Wattsi does.
> 
> Yeah, I think that may change in the long term. I will try to make time myself to write up a patch for it, if Tab doesn’t get to it first.

Update: I ended up making some time this weekend to work on that. I’m finishing up a Bikeshed patch for it. Once that got merged, we wouldn’t need the anno-positioning JavaScript code any longer — all that would be left is just the addEventListener wrap-anno toggle.

**Comment by sideshowbarker** [comment]
See https://github.com/tabatkins/bikeshed/pull/1711

**Comment by domenic** [comment]
FYI I'll put this on hold until https://github.com/tabatkins/bikeshed/pull/1711, but please let me know if you'd like to revisit that (e.g. because the Bikeshed review is taking too long) and I'm happy to jump back to it.

**Comment by sideshowbarker** [comment]
OK, reduced the patch/PR to just a single event listener

**Pull request merged**
