### PR TITLE
Force 0 exit status when running bikeshed for errors/warnings

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/whatwg/quirks/pull/30#issuecomment-414734994.

### CODE REVIEW

**Comment by annevk** [comment]
That seems better than not telling those making the PR what went wrong. I'm not sure why we'd optimize computers over humans.

**Comment by domenic** [comment]
The point is that you should bail if errors are detected and printed, instead of making the user wait for a second server round trip before the script exits.

**Comment by annevk** [comment]
Feel free to push a fixup, I don't really know what that would look like.

**Review by alauq — COMMENTED** [review]
[]()

**Pull request closed without merging**
