### PR TITLE
Move IRC wiki page to whatwg.org

### PR DESCRIPTION
**Pull request by GloverDonovan**
Hope I'm doing this right.

This is a direct copy of the IRC wiki page, but with one exception: I changed `irc://` to `ircs://` and added a colon before the `pre` block.

Ref #162

### CODE REVIEW

**Comment by annevk** [comment]
This will also require changes to other pages that link to the IRC page, such as the home page.

**Comment by GloverDonovan** [comment]
Decided to fix the IRC links directly in this pull request since there weren't as many other old links as I thought. Also updated the first commit to escape the `<` and `>` in the `pre` block.

**Comment by annevk** [comment]
Updated wiki.whatwg.org and blog.whatwg.org to reflect this change as well.

**Comment by domenic** [comment]
Looks really nice!

**Pull request merged**
